### ISSUE TITLE
Very quick doc?

### ISSUE THREAD

**Issue by lostinblue** [ashishhacker/TinuOS#1]
Can you put together the lines required to build and run it with qemu? Making it even slightly more accessible may bring more interest/help/peer-review. 

I was able to make build it without issue, but others would find this helpful I'm sure.

**Comment by lostinblue** [comment]
I did it for you, just needs to be added to the project as a README

```
git clone https://github.com/ashishhacker/TinuOS
cd TinuOS
make
cd iso/boot
qemu-system-x86_64 --kernel kernel
```

**Comment by lostinblue** [comment]
I made a pull request containing this with a little bit more

**Comment by ashishhacker** [comment]
@lostinblue thank you for showing your interest in this project. You can issue a pull request for add Qemu inside build process. I think that might be helpful :)
